print("please enter your name")
a=input()
print("please enter you friend's name")
b=input()
print("please enter you favourite place")
c=input()
print("please enter you hobby")
d=input()
print("{} went along with {} to visit {} and did {} there".format(a,b,c,d))
